deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Verify Current Directory
      run: pwd

    - name: List All Files and Folders in Current Directory
      run: ls -al

    - name: Check if dist directory exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory does not exist."
          exit 1
        fi

    - name: List build directory contents
      run: ls -al dist

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        npx gh-pages -d dist -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
